spring:
  application:
    name: mini-e-commere-hw2
  datasource:
    url: jdbc:postgresql://localhost:5433/mini-ecommerce
    username: postgres
    password: asdasd123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
server:
  port: 8080
jwt:
  expiration: 60000000
  secret: "twCdrIdw0rlhQt1WiSAzplkYspw6QzW09CxMmdMfAzwLAliuHMtoQrp5Xb9xy71nNkc8NFFU82KTpEgw3FyfWihtuPlTLsaQ9tSMrOsANQ"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
